<a href="https://colab.research.google.com/github/karunyajayaraman/Python_Fundamental_Quotes/blob/main/Python_DA_Assignment_1%E2%80%94Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Module -5
#Python DA Assignment 1—Numpy and Pandas

Numpy Array Operations:

In [ ]:
import numpy as np

In [ ]:
# 1. Create a 1D NumPy Array:

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9], dtype = float)

print(f'Week1_Temperatures :',temperatures_w1)
temperatures_w1

Week1_Temperatures : [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
# 2. Inspection and Properties:

print(f'Shape of Temperatures_W1 : ',(temperatures_w1).shape)
print(f'DataType : ',(temperatures_w1).dtype)
print(f'Number of elements in the array : ',(temperatures_w1).size)

Shape of Temperatures_W1 :  (7,)
DataType :  float64
Number of elements in the array :  7


In [ ]:
# 3. Array Operations:

#Celsius to Fahrenheit - (Fahrenheit = (Celsius * 9/5) + 32)

temperatures_w1

Fahrenheit_w1 = ((temperatures_w1 * 9/5)+32)

print('Fahrenheit of Week1 :',Fahrenheit_w1)
print('Temperature of Week1 :',temperatures_w1)

print('\n*****Temperatures for the week*****')
print('\nMinimum :',temperatures_w1.min())
print('Maximum :',temperatures_w1.max())
print('Mean :',round(temperatures_w1.mean(),2))   # Mean : 74.37714285714286


Fahrenheit of Week1 : [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Temperature of Week1 : [22.5 25.3 20.8 23.4 26.1 24.8 21.9]

*****Temperatures for the week*****

Minimum : 20.8
Maximum : 26.1
Mean : 23.54


In [ ]:
# 4. Array Slicing and Indexing:

print("Temperatures of the Week")
print('\nFirst three days of the week :',temperatures_w1[:3])
print('Weekend (last two days) :',temperatures_w1[5:])     # [-2:]  also in negative indexing
print('Middle Three days of the week :',temperatures_w1[2:5])


Temperatures of the Week

First three days of the week : [22.5 25.3 20.8]
Weekend (last two days) : [24.8 21.9]
Middle Three days of the week : [20.8 23.4 26.1]


In [ ]:
# 5. Create a 2D Array:

#Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)

#Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] ,
                        [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]]
                        ,dtype = float)
temperatures

print("Temperatures of Week 1 & 2 : ",temperatures)

Temperatures of Week 1 & 2 :  [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [ ]:
# 6. Inspect and Slice the 2D Array:

print(f'Shape of Temperatures : {(temperatures).shape}')
print(f'DataType : {(temperatures).dtype}')
print(f'Number of elements in the array : {(temperatures).size}')

print(f'\nWeek 1 - Temperature : {temperatures[0]}')
print(f'Week 2 - Temperature : {temperatures[1]}')

print(f'\nWeekends Temperature(Last 2 days):\n{temperatures[0:,5:]}')

Shape of Temperatures : (2, 7)
DataType : float64
Number of elements in the array : 14

Week 1 - Temperature : [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 - Temperature : [19.2 22.5 21.3 24.  23.5 22.8 20.1]

Weekends Temperature(Last 2 days):
[[24.8 21.9]
 [22.8 20.1]]


#Pandas Series:


In [ ]:
#Importing pandas
import pandas as pd

In [ ]:
# 1. Creating Pandas Series:

marks = [95, 92, 89, 85, 80]
ranks = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']

scores = pd.Series(marks, index= ranks)
print(scores)
scores

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


,0
Rank1,95
Rank2,92
Rank3,89
Rank4,85
Rank5,80


In [ ]:
# 2. Indexing and Slicing:

# For the Pandas Series 'scores':

print(f'\nMark of the 1st rank student (from Series) : {scores.iloc[0]}')  # Integer Index Position(pandas)

print(f'\nMarks of the Top 3 ranks (from Series): \n{scores.loc['Rank1':'Rank3']}')  #Rank by Label using loc

print(f'\nMark of the 3rd-ranked student : \n {scores.iloc[2]}') #iloc - integer location

print(f'\nMarks are greater than 90 : \n{scores.loc[scores > 90]}')




Mark of the 1st rank student (from Series) : 95

Marks of the Top 3 ranks (from Series): 
Rank1    95
Rank2    92
Rank3    89
dtype: int64

Mark of the 3rd-ranked student : 
 89

Marks are greater than 90 : 
Rank1    95
Rank2    92
dtype: int64


In [ ]:
# 3. Manipulating Series:
scores

,0
Rank1,95
Rank2,92
Rank3,89
Rank4,85
Rank5,80


In [ ]:
# Modify - 1st rank to 100.

scores.loc['Rank1'] = 100
scores

print(f'\nModified the 1st rank(100) : \n{scores}')


Modified the 1st rank(100) : 
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [ ]:
# Remove the Last Rank from the Series - use DROP

# scores.drop('Rank5')  # Direct method
# scores.index[-1] - select the last rank from the series(way to used for large set of datas)

print(f'\nRemove the Last rank :\n{scores.drop(scores.index[-1])}')


Remove the Last rank :
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [ ]:
# CGPA - Divide the mark in the Series by 10

cgpa = scores / 10  # Vectorized operations

print(f'\nCGPA :\n{cgpa}')


CGPA :
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Rank5     8.0
dtype: float64


#Pandas DataFrame:

In [ ]:
# Dictionary

transactions = {'TransactionID' : [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
                'ProductCategory':['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
                'Region' : ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
                'Amount' : [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
              }
transactions

{'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
 'ProductCategory': ['Electronics',
  'Clothing',
  'Electronics',
  'Furniture',
  'Clothing',
  'Electronics',
  'Furniture',
  'Clothing',
  'Furniture',
  'Electronics'],
 'Region': ['North',
  'South',
  'North',
  'East',
  'West',
  'North',
  'East',
  'West',
  'South',
  'North'],
 'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]}

In [ ]:
# 1. Creating Pandas DataFrame:

transactions = pd.DataFrame(transactions)
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [ ]:
# 2. Data Exploration:

#Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types.

# Head()

print("******Basic Information*****")

print(f'\nFirst 5 Rows \n')

transactions.head()

******Basic Information*****

First 5 Rows 



,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200


In [ ]:
#Tail()

print(f'\nLast 5 Rows \n')

transactions.tail()


Last 5 Rows 



,TransactionID,ProductCategory,Region,Amount
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [ ]:
#Shape

print(f'\nShape of Transactions : {transactions.shape}')


Shape of Transactions : (10, 4)


In [ ]:
# Column Names:

print(f'\nColumn Name of Transactions :\n\n{transactions.columns}')


Column Name of Transactions :

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [ ]:
# DataTypes of each column

print(f'\nColumn Name of Transactions\n')
transactions.dtypes


Column Name of Transactions



,0
TransactionID,int64
ProductCategory,object
Region,object
Amount,int64


In [ ]:
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [ ]:
# Display only the 'ProductCategory' and 'Amount' columns.

transactions[['ProductCategory', 'Amount']]


,ProductCategory,Amount
0,Electronics,200
1,Clothing,150
2,Electronics,300
3,Furniture,450
4,Clothing,200
5,Electronics,250
6,Furniture,300
7,Clothing,180
8,Furniture,350
9,Electronics,400


In [ ]:
# Retrieve the last 3 columns of the DataFrame using iloc or loc.

transactions.iloc[0:,-3:]  # Syntax: df.iloc[row_selection, column_selection]

#transactions.iloc[ : ,1:]

,ProductCategory,Region,Amount
0,Electronics,North,200
1,Clothing,South,150
2,Electronics,North,300
3,Furniture,East,450
4,Clothing,West,200
5,Electronics,North,250
6,Furniture,East,300
7,Clothing,West,180
8,Furniture,South,350
9,Electronics,North,400


In [ ]:
# Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]

#print(f'Greater than 200 from North-Region :\n{transactions[(transactions['Region']=='North')&(transactions['Amount']>200)]}')

,TransactionID,ProductCategory,Region,Amount
2,103,Electronics,North,300
5,106,Electronics,North,250
9,110,Electronics,North,400


In [ ]:
# Find the value counts for the 'ProductCategory' column.

transactions["ProductCategory"].value_counts().reset_index()

# print(f'Value counts for Product category :\n\n{transactions["ProductCategory"].value_counts()}')

,ProductCategory,count
0,Electronics,4
1,Clothing,3
2,Furniture,3


In [ ]:
# Find the unique values in the 'Region' column

print(f'Unique values from Region : {transactions["Region"].unique()}')


Unique values from Region : ['North' 'South' 'East' 'West']


In [ ]:
# Group by 'Region' and find the mean amount for each region

transactions.groupby('Region')['Amount'].mean().reset_index()

,Region,Amount
0,East,375.0
1,North,287.5
2,South,250.0
3,West,190.0


# 3. Manipulating the DataFrame:

In [ ]:
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [ ]:
# Modify the 'Amount' for the transaction with TransactionID 102 to 165

transactions.iloc[1,0] = 165
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,165,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [ ]:
# Add a new column 'Discount' by calculating 10% of the 'Amount'

transactions['Discount'] = transactions['Amount'] * 0.10

#print(f"Updated DataFrame:\n\n{transactions}")

print(f"Updated DataFrame\n")

transactions

Updated DataFrame



,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,165,Clothing,South,150,15.0
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
8,109,Furniture,South,350,35.0
9,110,Electronics,North,400,40.0


In [ ]:
# Remove the row with TransactionID 109

transactions = transactions.drop(8)
transactions


,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,165,Clothing,South,150,15.0
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


In [ ]:
# Delete the 'Discount' column from the DataFrame

#transactions = transactions.drop(columns = 'Discount')

transactions = transactions.drop(columns='Discount')

transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,165,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
9,110,Electronics,North,400


In [ ]:
print(transactions.columns)

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
